services:
  arma-server-web-gui:
    image: aquerr/arma-server-web-gui
    restart: unless-stopped
    ports:
      - "8085:8085"
    volumes:
      - /arma-server:/aswg/arma-server
      - /config:/aswg/config
      - /aswg_profiles:/aswg/aswg_profiles
